puts "enter two integer value: "
x= gets.to_i
y= gets.to_i
puts "addition= #{x+y}"
puts "substraction= #{x-y}"
puts "multiplication= #{x*y}"
puts "division= #{x/y}"
puts "modulus= #{x%y}"
puts "exponant= #{x**y}"
puts "double equal= #{x==y}"
puts "not equal= #{x!=y}"
puts "greater than= #{x>y}"
puts "less than= #{x<y}"
puts "greater than or equal to= #{x>=y}"
puts "less than or equal to= #{x<=y}"
puts "Combined comparison operator= #{x<=>y}"
puts "equality= #{x===y}"
puts "same type and equal values= #{x.eql?y}"
puts "same object id=#{x.equal?y}"
puts "AND= #{x & y}"
puts "OR= #{x | y}"
puts "XOR= #{x ^ y}"
puts "Binary Ones Complement= #{x ~ y}"